version: '3'

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres/db/:/var/lib/postgresql/data/

  server:
    image: 'open-stock/server'
    # build:
    #   context: ./packages/server/
    depends_on:
      - postgres
    # network_mode: host
    ports:
      - 4000:4000
  webui:
    image: 'open-stock/webui'
    # build:
    #   context: ./packages/webui/
    depends_on:
      - server
    # network_mode: host
    ports:
      - 5173:5173
