version: '3'

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres/db/:/var/lib/postgresql/data/

  server:
    build:
      context: ./packages/server/
    depends_on:
      - postgres
    ports:
      - 4000:4000 
  webui:
    build:
      context: ./packages/webui/
    depends_on:
      - server
    ports:
      - 4173:4173 
