version: '3'

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres/db/:/var/lib/postgresql/data/

  # server:
  #   image: 'node:16'
  #   build:
  #     context: ./packages/server/
  #   depends_on:
  #     - postgres
  #   network_mode: host
  #   ports:
  #     - 4000:4000
  # webui:
  #   image: 'node:16'
  #   build:
  #     context: ./packages/webui/
  #   depends_on:
  #     - server
  #   network_mode: host
  #   ports:
  #     - 4173:4173
