version: '3'

services:
  webui:
    depends_on:
      - server
    build:
      context: ./packages/webui/
    ports:
      - 5173:5173

  server:
    depends_on:
      - database
    build:
      context: ./packages/server/
    ports:
      - 4000:4000
    env_file:
      - .env

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres/db/:/var/lib/postgresql/data/
