import { PrismaClient } from '@prisma/client'
import { v4 as uuidv4 } from 'uuid'

import { Part } from '@prisma/client'

const prisma = new PrismaClient()

// const partData = {
//   id: uuidv4(),
//   brand: 'brand',
//   name: 'part name',
//   model: 'model number',
//   description: 'part description',
//   bin: '01',
//   container: 'A1',
//   location: 'location',
//   quantity: 0,
//   tags: ['tag1', 'tag2', 'tag3'],
// };
//

const partData = [
  {
    id: 'f83eedae-cb14-453d-acc0-c37377838041',
    brand: 'none',
    name: 'small power switch',
    model: 'none',
    description: 'Small power switches',
    bin: 'A1',
    container: '01',
    location: 'closet',
    quantity: 75,
    tags: ['power', 'switch'],
    __typename: 'Part',
  },
  {
    id: '47b66089-0dff-43a7-845d-1dd104b98168',
    brand: 'none',
    name: 'Momentary Push Button Tactile Switch',
    model: 'none',
    description:
      'Surface Mounted 4-Terminal Momentary Push Button Tactile Switch, 5 mm x 5 mm x 1.5 mm ',
    bin: 'A1',
    container: '01',
    location: 'closet',
    quantity: 68,
    tags: ['tact-switch', 'button'],
    __typename: 'Part',
  },
  {
    id: '049f8eb7-79eb-463d-87fb-ba66b578753d',
    brand: 'uxcell',
    name: 'Momentary Push Button Tactile Switch',
    model: 'none',
    description:
      '5x5x1.5mm Momentary PCB Surface Mounted Devices SMT Mount 4 Pins Push Button SPST Tactile Tact Switch ',
    bin: 'A1',
    container: '01',
    location: 'closet',
    quantity: 30,
    tags: ['tact-switch', 'button'],
    __typename: 'Part',
  },
  {
    id: '421c4fb9-9d62-4b3f-88db-11e96da4402d',
    brand: 'none',
    name: 'Red Led',
    model: 'Red',
    description: 'Red Led',
    bin: 'C1',
    container: '01',
    location: 'closet',
    quantity: 12,
    tags: ['electrical', 'led', 'light'],
    __typename: 'Part',
  },
  {
    id: 'bdf6a8d4-4d9f-46df-b66f-8e0bfa0c98f7',
    brand: 'none',
    name: 'Diodes',
    model: 'none',
    description: 'Diodes',
    bin: 'C1',
    container: '01',
    location: 'closet',
    quantity: 3,
    tags: ['electrical', 'diodes'],
    __typename: 'Part',
  },
  {
    id: '48dcc9be-b8e0-44b6-884b-cd20fa84a1e2',
    brand: 'none',
    name: 'Small LED light strip',
    model: 'none',
    description: 'Small LED light strip',
    bin: 'C1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['electrical', 'led', 'light'],
    __typename: 'Part',
  },
  {
    id: 'd9ddd857-c8b8-4706-9329-0d593fa002be',
    brand: 'none',
    name: 'rubber dome tact switch',
    model: 'none',
    description: 'Rubber dome tact switch',
    bin: 'A1',
    container: '01',
    location: 'closet',
    quantity: 11,
    tags: ['tact-switch', 'rubber', 'dome'],
    __typename: 'Part',
  },
  {
    id: '4ba06518-8700-4f5e-a4fc-f35db0f20fab',
    brand: 'none',
    name: 'Momentary Push Button Tactile Switch',
    model: 'none',
    description: 'Momentary Push Button Tactile Switch, 6 mm x 6 mm x 6 mm ',
    bin: 'A1',
    container: '01',
    location: 'closet',
    quantity: 13,
    tags: ['tact-switch', 'button'],
    __typename: 'Part',
  },
  {
    id: 'ae146ead-7c6c-4562-8310-eda0a4891e24',
    brand: 'none',
    name: 'Misc. Hardware',
    model: 'none',
    description:
      'Misc. Hardware\n\nScrews, nuts, bolts, standoffs, washers, etc.',
    bin: 'A2',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['misc', 'hardware', 'nuts', 'bolts', 'washers', 'stand-offs'],
    __typename: 'Part',
  },
  {
    id: '9dc5758f-3439-40ad-8ae6-de603e63bd2d',
    brand: 'none',
    name: 'small compression spring',
    model: 'none',
    description: 'Small compression springs',
    bin: 'A3',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['spring', 'compression', 'small'],
    __typename: 'Part',
  },
  {
    id: '328b779f-0a62-4f8c-988e-1c6a1eee2764',
    brand: 'uxcell',
    name: 'Radial Ball Bearing',
    model: 'none',
    description:
      'uxcell a13061400ux0831 10 Pcs 625ZZ 5mm x 16mm x 5mm Shielded Deep Groove Radial Ball Bearing ',
    bin: 'A3',
    container: '01',
    location: 'closet',
    quantity: 8,
    tags: ['radial', 'bearing'],
    __typename: 'Part',
  },
  {
    id: '5441baaa-d0a3-4daf-908f-bee05649b3b0',
    brand: 'uxcell',
    name: 'Radial Ball Bearing',
    model: '608',
    description:
      'VXB 608ZZ Set of 8 Skateboard Bearing 608Z Shielded Ball Bearings',
    bin: 'A3',
    container: '01',
    location: 'closet',
    quantity: 3,
    tags: ['radial', 'bearing', '608'],
    __typename: 'Part',
  },
  {
    id: 'b4bbef9a-d18e-48c7-81bc-78bfc7f5a1b1',
    brand: 'FINDMAG',
    name: '5x3mm Magnet',
    model: '5x3mm',
    description: 'Magnets, 5x3mm',
    bin: 'A3',
    container: '01',
    location: 'closet',
    quantity: 62,
    tags: ['magnet'],
    __typename: 'Part',
  },
  {
    id: '66aa9a99-2e4d-4c50-9efb-e966f8f8de71',
    brand: 'none',
    name: 'Misc. Magnets',
    model: 'none',
    description: 'Misc. Magnets',
    bin: 'A3',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['misc', 'magnets'],
    __typename: 'Part',
  },
  {
    id: 'ca380494-b231-4c70-9820-88bd2c226918',
    brand: 'Yaxi',
    name: 'Yaxi Earpads',
    model: 'Black',
    description: 'YAXI EARPADS for Koss PORTAPRO (Black) ',
    bin: 'A4',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['Yaxi', 'Earpads'],
    __typename: 'Part',
  },
  {
    id: '569bd881-8b65-4e2f-9fd9-fcf9eb6de90f',
    brand: 'Sunmns',
    name: '40mm Earpads',
    model: 'Black',
    description:
      'Sunmns 40mm Earpads Ear Pad Foam Cushion Cover Compatible with Motorola S305/ Sony Q21 Q23 Q23/ MDR-Q22LP/ MDR-Q33/ Panasonic RR930/ Logitech H555 Headphones, 5 Pairs, 1.61 x 1.61 x 0.31 inches',
    bin: 'A4',
    container: '01',
    location: 'closet',
    quantity: 8,
    tags: ['Earpads'],
    __typename: 'Part',
  },
  {
    id: '4a9ddb7f-28d5-4db0-804f-965782e2518d',
    brand: 'none',
    name: 'Audio Adapter 6.35mm',
    model: 'none',
    description:
      'Audio Adapter 6.35mm (1/4 inch) Male to 3.5mm (1/8 inch) Female Stereo Headphone Connector',
    bin: 'A4',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['Audio', 'Adapter'],
    __typename: 'Part',
  },
  {
    id: '14d76e41-0548-4d44-b066-d2374bec5a8d',
    brand: 'none',
    name: 'Misc. Nuts and Bolts',
    model: 'none',
    description: 'Misc. Nuts and bolts.',
    bin: 'B1',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['Misc', 'hardware', 'nuts', 'bolts'],
    __typename: 'Part',
  },
  {
    id: '165d4093-15be-4701-90a9-bc5dc11baaf9',
    brand: 'none',
    name: 'PC Screws',
    model: 'none',
    description: 'PC Misc. Screws',
    bin: 'B2',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['Misc', 'PC'],
    __typename: 'Part',
  },
  {
    id: 'f1c7474b-fcfa-4864-ab45-7e1b564079e8',
    brand: 'Arctic Silver',
    name: 'Arctic Silver 5',
    model: 'Arctic Silver 5',
    description: 'Arctic Silver 5 Thermal Paste',
    bin: 'B2',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['PC', 'thermal', 'paste'],
    __typename: 'Part',
  },
  {
    id: '921092ed-7026-48b2-9451-2ea9b5519c10',
    brand: 'none',
    name: 'Wire Crimps',
    model: 'none',
    description: 'Wire crimps',
    bin: 'B3',
    container: '01',
    location: 'closet',
    quantity: 12,
    tags: ['electrical', 'crimps'],
    __typename: 'Part',
  },
  {
    id: '478aa450-64d2-40f8-9c73-ee3ad659761f',
    brand: 'Gardner Bender',
    name: 'Ring Terminal',
    model: 'none',
    description: '16-14 AWG Ring Terminals',
    bin: 'B3',
    container: '01',
    location: 'closet',
    quantity: 22,
    tags: ['electrical', 'ring', 'terminal'],
    __typename: 'Part',
  },
  {
    id: 'db1e49a5-8755-4c85-b8f0-fa8652872500',
    brand: 'none',
    name: 'Quick Connector',
    model: 'none',
    description: 'Wire quick connectors',
    bin: 'B3',
    container: '01',
    location: 'closet',
    quantity: 3,
    tags: ['electrical', 'quick', 'connector'],
    __typename: 'Part',
  },
  {
    id: 'e3c37702-ee5f-4ff9-830b-e7658c4d1966',
    brand: 'Tulead',
    name: '12V DC Solenoid',
    model: '12V DC Solenoid',
    description:
      'Tulead 12V DC Solenoid Pull Push Electronic Actuator Micro Solenoid Electromagnet 5N Suction ',
    bin: 'B4',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['solenoid'],
    __typename: 'Part',
  },
  {
    id: 'f8373f08-a9e4-442a-a88f-67e8af7a713f',
    brand: 'Topoox',
    name: 'Mini Electric Motor',
    model: 'DC 1.5-3V 15000RPM Mini Electric Motor',
    description: 'Topoox 6 Pack DC 1.5-3V 15000RPM Mini Electric Motor',
    bin: 'B4',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['electric', 'motor'],
    __typename: 'Part',
  },
  {
    id: 'e350e54e-9e8e-4290-8104-2de1d62be14a',
    brand: 'ATNSINC',
    name: '28BYJ-48 Stepper Motor',
    model: '28BYJ-48',
    description: '6 PCS 28BYJ-48 ULN2003 5V Stepper Motor',
    bin: 'A5',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['stepper', 'motor'],
    __typename: 'Part',
  },
  {
    id: '2e2f515b-f2bd-4594-8a03-8f3fd5d5271d',
    brand: 'ATNSINC',
    name: 'ULN2003 Driver Board',
    model: 'ULN2003',
    description: 'ULN2003 Driver Board',
    bin: 'A5',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['motor', 'driver', 'stepper'],
    __typename: 'Part',
  },
  {
    id: '0294ba92-208b-4ce0-a753-24f8acef0316',
    brand: 'none',
    name: '200K Ohm Resistor',
    model: 'Fixed Resistor',
    description:
      '200K Ohm Resistor Color Code: Red, Black, Yellow, Golden. Resistance: 200K Ohm, Power Rating: 0.25 Watt, Approximate Maximum Current: 1.12mA',
    bin: 'C1',
    container: '01',
    location: 'closet',
    quantity: 75,
    tags: ['electrical', 'resistor'],
    __typename: 'Part',
  },
  {
    id: '956691de-182b-421d-bde4-657b1945e379',
    brand: 'RadioShack',
    name: 'Rectangular Blue LED',
    model: '276-0013',
    description: 'Super High Brightness Rectangular Blue LED',
    bin: 'C1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['electrical', 'led', 'light'],
    __typename: 'Part',
  },
  {
    id: 'fdba57a9-5d4e-43f0-87ae-1d76d09be0e5',
    brand: 'Deegoo',
    name: 'MG996R Digital Servo',
    model: 'MG996R',
    description:
      'Deegoo [4-Pack] MG996R 55g Metal Gear Torque Digital Servo Motor',
    bin: 'C2',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['Servo'],
    __typename: 'Part',
  },
  {
    id: '4cb3c155-4afc-4df3-ae06-19eb1139e29a',
    brand: 'Philmore',
    name: '2.5mm DC Barrel Jack',
    model: '48-1297',
    description:
      '2.5mm DC Power Jack to solderless terminal. Accepts up to 14AWG wire.',
    bin: 'C3',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['electrical', 'power'],
    __typename: 'Part',
  },
  {
    id: 'a5c7bf4c-18ff-45fb-830a-e7a6bc8e2bb6',
    brand: 'Deegoo',
    name: 'MG996R Electric Motor',
    model: 'MG996R Converted',
    description: 'MG996R Converted to high torque electric motors',
    bin: 'C4',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['electrical', 'motor'],
    __typename: 'Part',
  },
  {
    id: 'c22df567-f4e6-4076-834d-860db4192189',
    brand: 'none',
    name: '3.5" composite screen',
    model: 'none',
    description: '3.5" composite screen',
    bin: 'A6',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['screen'],
    __typename: 'Part',
  },
  {
    id: '16d08408-c5a0-42dc-8ccf-bb27565f8895',
    brand: 'none',
    name: '5" composite screen',
    model: 'none',
    description: '5" composite screen',
    bin: 'A6',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['screen'],
    __typename: 'Part',
  },
  {
    id: 'bebf9c11-7a88-4502-9fe9-cc65510ad149',
    brand: 'none',
    name: 'L293D Motor Controller',
    model: 'L293D',
    description: 'L293D 16pin motor controller',
    bin: 'D1',
    container: '01',
    location: 'closet',
    quantity: 7,
    tags: ['electrical', 'motor', 'controller', 'ic'],
    __typename: 'Part',
  },
  {
    id: '8b1c2439-5b31-4311-8c25-945cb39aa1d3',
    brand: 'KIALEDI',
    name: 'SG90 Servo Motor',
    model: 'SG90',
    description: 'Servo Motor SG90 Tower Pro 9g',
    bin: 'D2',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['servo'],
    __typename: 'Part',
  },
  {
    id: '41f7b2ee-7bac-4873-805a-c094e4e5558a',
    brand: 'none',
    name: 'Disassembled mp3 player',
    model: 'none',
    description: 'Disassembled mp3 player',
    bin: 'D3',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['mp3', 'player'],
    __typename: 'Part',
  },
  {
    id: 'c177141d-7a0c-4d70-84e1-206c460e8eb6',
    brand: 'none',
    name: 'Disassembled bluetooth controller',
    model: 'bluetooth controller',
    description: 'Disassembled bluetooth controller',
    bin: 'D3',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['bluetooth', 'controller'],
    __typename: 'Part',
  },
  {
    id: '1d03ff2c-33f5-4fa9-a349-dbdd46f7f294',
    brand: 'Sony',
    name: 'PSP analog stick',
    model: 'PSP analog stick',
    description: 'PSP analog stick',
    bin: 'D3',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['psp', 'game', 'analog', 'stick'],
    __typename: 'Part',
  },
  {
    id: '9231bb2a-7a89-4379-ac64-7a4fba30e0e6',
    brand: 'ANMBEST',
    name: 'USB C Port - Male',
    model: 'USB C Port - Male',
    description: 'USB C Port - Male with breakout',
    bin: 'D4',
    container: '01',
    location: 'closet',
    quantity: 4,
    tags: ['usb', 'c', 'breakout', 'power', 'charging'],
    __typename: 'Part',
  },
  {
    id: 'd57f7344-d638-45b4-9e7d-b77b8d499a7b',
    brand: 'none',
    name: 'USB A Port - Female',
    model: 'USB A Port - Female',
    description: 'USB A Port - Female',
    bin: 'D4',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['usb', 'a', 'power', 'charging'],
    __typename: 'Part',
  },
  {
    id: '4848fcb5-bf32-495c-9327-73b8a49dc783',
    brand: 'HiLetgo',
    name: 'FTDI Programmer',
    model: 'FT232RL',
    description:
      'HiLetgo FT232RL FTDI Mini USB to TTL Serial Converter Adapter Module 3.3V 5.5V FT232R Breakout FT232RL USB to Serial Mini USB to TTL Adapter Board',
    bin: 'E1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['ftdi', 'programmer', 'adapter', 'serial'],
    __typename: 'Part',
  },
  {
    id: '285ae873-d861-468b-b5fc-2193b82d38e3',
    brand: 'Aideepen',
    name: 'FT232RL V2.0',
    model: 'FT232RL V2.0',
    description:
      'Aideepen FT232RL V2.0 Micro USB to TTL Serial Breakout Adapter Module Converter',
    bin: 'E1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['adapter', 'serial'],
    __typename: 'Part',
  },
  {
    id: '6203057d-39c6-4213-9e68-d36b50ee95c7',
    brand: 'LICHIFIT',
    name: 'Game Cube SD2SP2',
    model: 'Game Cube SD2SP2',
    description:
      ' LICHIFIT Professional Micro SD Card Adapter TF Card Reader for Game Cube SD2SP2 SDLoad SDL Adapter (Blue) ',
    bin: 'E1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['gamecube', 'adapter'],
    __typename: 'Part',
  },
  {
    id: 'cc2cac72-758b-46bc-93b4-97b959065e46',
    brand: 'XenoGC',
    name: 'XenoGC',
    model: 'XenoGC',
    description: 'XenoGC is a drivechip for the Nintendo Gamecube.',
    bin: 'E1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['gamecube', 'modchip'],
    __typename: 'Part',
  },
  {
    id: '9cf5bdab-9298-4040-8fbb-a7cd0708da2e',
    brand: 'Adafruit',
    name: 'Mono Audio Amplifier',
    model: 'PAM8302',
    description:
      'Audio IC Development Tools Adafruit Mono 2.5W Class D Audio Amplifier - PAM8302',
    bin: 'E1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['audio', 'amp', 'mono'],
    __typename: 'Part',
  },
  {
    id: '203e2317-b38f-43d8-8eb6-a05c6ef458da',
    brand: 'SH',
    name: 'Toggle Switch',
    model: '9345',
    description: 'Toggle Switch - 8A250V - 16A125V - 1HP 125V',
    bin: 'E2',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['toggle', 'switch', 'electrical', 'power'],
    __typename: 'Part',
  },
  {
    id: '4f6b8405-6225-4a24-acb6-96c66163391b',
    brand: 'none',
    name: 'Rocker Switch',
    model: 'none',
    description: 'Rocker Switch - 10A 250VAC - 20A 128VAC',
    bin: 'E2',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['rocker', 'switch', 'electrical', 'power'],
    __typename: 'Part',
  },
  {
    id: 'e1611bd3-ba8d-4747-8619-e58f65a9c3ef',
    brand: 'none',
    name: 'sh Button',
    model: 'Push Button',
    description: 'Momentary Push Button',
    bin: 'E2',
    container: '01',
    location: 'closet',
    quantity: 3,
    tags: ['button', 'electical'],
    __typename: 'Part',
  },
  {
    id: '436ee303-6d4f-42c7-8f36-72298fb43d22',
    brand: 'none',
    name: 'Rocker Switch',
    model: 'none',
    description: 'Rocker Switch',
    bin: 'E2',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['rocker', 'switch', 'electrical', 'power'],
    __typename: 'Part',
  },
  {
    id: '0bd75f48-cbe9-4a22-afd1-bb8cf5136225',
    brand: 'none',
    name: 'Wifi antenna',
    model: 'Wifi antenna',
    description: 'Wifi antenna',
    bin: 'E3',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['wifi', 'antenna'],
    __typename: 'Part',
  },
  {
    id: 'cefc42b1-f8cb-4ea9-9995-1405a7d96fcd',
    brand: 'none',
    name: 'Small Heatsinks',
    model: 'none',
    description: 'Small Heatsinks',
    bin: 'E3',
    container: '01',
    location: 'closet',
    quantity: 7,
    tags: ['heatsinks', 'cooling'],
    __typename: 'Part',
  },
  {
    id: '7917e9ad-eb9d-4a9a-8a7d-dd28baf969b7',
    brand: 'Adafruit',
    name: 'Mini Metal Speaker',
    model: 'Mini Metal Speaker',
    description: 'Mini Metal Speaker w/ Wires - 8 ohm 0.5W',
    bin: 'E3',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['speaker', 'audio'],
    __typename: 'Part',
  },
  {
    id: 'e417bcfb-bf79-441b-9d01-67d67be93902',
    brand: 'ANMBEST',
    name: 'USB C Port - Female',
    model: 'USB C Port - Female',
    description: 'USB C Port - Female with breakout',
    bin: 'D4',
    container: '01',
    location: 'closet',
    quantity: 12,
    tags: ['usb', 'c', 'breakout', 'power', 'charging'],
    __typename: 'Part',
  },
  {
    id: 'b8483f15-0d4a-4ce8-87e0-ed20c062b499',
    brand: 'none',
    name: 'Servo Adapters',
    model: 'none',
    description: 'Misc. Servo adapters and connections',
    bin: 'A7',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['misc', 'servo', 'adapters'],
    __typename: 'Part',
  },
  {
    id: '9f0f4986-1e76-4152-b6c2-26d5664f6c72',
    brand: 'none',
    name: 'Potentiometer',
    model: 'none',
    description: 'Potentiometer',
    bin: 'A7',
    container: '01',
    location: 'closet',
    quantity: 4,
    tags: ['electrical', 'resistor'],
    __typename: 'Part',
  },
  {
    id: '22579918-91a0-4562-9dc1-032eb431a35f',
    brand: 'DAOKI',
    name: '5V Battery Charging Protection Board',
    model: '134N3P',
    description:
      'DAOKI 5V Battery Charging Protection Board 1A Boost Step Up Power Supply Module 134N3P Lithium Battery Li-ion Charger Board',
    bin: 'E4',
    container: '01',
    location: 'closet',
    quantity: 5,
    tags: ['charging', 'power', 'electrical'],
    __typename: 'Part',
  },
  {
    id: 'a56d9708-5ae3-4d49-9b33-fc1c06b32ada',
    brand: 'Tenergy',
    name: 'AA 2000mAh NiMH',
    model: 'P/N 10306',
    description: 'Tenergy AA 2000mAh NiMH Flat Top Rechargeable Battery',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 4,
    tags: ['battery', 'power', 'electrical'],
    __typename: 'Part',
  },
  {
    id: '0ad84dc8-ec8f-4980-a96a-8b5823175ca1',
    brand: 'none',
    name: 'Li-ion Battery Pack',
    model: 'none',
    description: 'Li-ion battery pack - 3.7v - 570mAH/2Wh',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['battery', 'power', 'electrical'],
    __typename: 'Part',
  },
  {
    id: 'be331827-860f-44ab-8aac-a6547b0f9054',
    brand: 'Synergy Digital',
    name: 'Synergy Digital Cordless Phone Battery',
    model: 'HGB-15AAx3',
    description:
      'Synergy Digital Cordless Phone Battery, Works with Huawei BTR2260B Cordless Phone, (Ni-MH, 3.6V, 1600 mAh) Ultra Hi-Capacity Battery ',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['battery', 'power', 'electrical'],
    __typename: 'Part',
  },
  {
    id: 'f3b912a9-a8f7-40aa-992e-9daf4cb456a3',
    brand: 'Adafruit',
    name: 'Adafruit 328 Battery',
    model: 'Adafruit 328 Battery',
    description:
      'Adafruit 328 Battery, Lithium Ion Polymer, 3.7V, 2500mAh, 2" x 2.55" x 0.30" Size',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['battery', 'power', 'electrical'],
    __typename: 'Part',
  },
  {
    id: '5fe22726-31f5-476e-96e5-e3b86f371bfd',
    brand: 'none',
    name: 'SP65M 3.7V 2210mAh Battery',
    model: 'SP65M',
    description:
      'SP65M 3.7V 2210mAh Battery Replacement for Sony Playstation PS Vita PCH-1001 PCH-1101 1003 1103',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['battery', 'power', 'electrical'],
    __typename: 'Part',
  },
  {
    id: 'aff3cc8f-a0a3-402a-a2ec-69fad2a60d1b',
    brand: 'none',
    name: 'Battery - 3.7V 4000MAH',
    model: '805080 3.7V 4000MAH',
    description: '805080 3.7V 4000MAH Polymer cell battery',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['battery', 'power', 'electrical'],
    __typename: 'Part',
  },
  {
    id: '4ece5a0f-53d5-4bfe-bc65-aabc54618d40',
    brand: 'none',
    name: 'IDE Cable',
    model: 'IDE Cable',
    description: 'IDE Cable',
    bin: 'C6',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['IDE', 'wire'],
    __typename: 'Part',
  },
  {
    id: '0b7aab88-e178-4e66-9a86-4608d46a29ca',
    brand: 'none',
    name: 'Misc. Wire',
    model: 'none',
    description: 'Misc. Wire',
    bin: 'C6',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['misc', 'wire'],
    __typename: 'Part',
  },
  {
    id: '09eaeeb2-e0f5-4615-b59d-a8b016a58faa',
    brand: 'none',
    name: '3.5mm Headphone Jack (TRRS)',
    model: 'none',
    description: '3.5mm TRRS headphone jack',
    bin: 'A4',
    container: '01',
    location: 'closet',
    quantity: 3,
    tags: ['trrs'],
    __typename: 'Part',
  },
  {
    id: 'a3dfe546-94cb-41cf-adec-d3517f0f92fc',
    brand: 'none',
    name: 'Misc. Power Connectors',
    model: 'none',
    description: 'Misc. Power Connectors',
    bin: 'C6',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['misc', 'connectors'],
    __typename: 'Part',
  },
  {
    id: '1c20211e-843f-49d5-aa16-127726aa6c62',
    brand: 'none',
    name: 'Male Barrel Jack Plugs',
    model: 'none',
    description: 'Variable Male Barrel Jack Plugs of different sizes',
    bin: 'C3',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['barrel', 'jack', 'power', 'electrical'],
    __typename: 'Part',
  },
  {
    id: 'c993a8f4-3d06-41de-8bc7-67fde1722593',
    brand: 'Adafruit',
    name: 'PiGRRL 2.0 Custom Gamepad PCB',
    model: 'Product ID: 3015',
    description: 'PiGRRL 2.0 Custom Gamepad PCB',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['gamepad', 'buttons', 'pigrrl'],
    __typename: 'Part',
  },
  {
    id: '39556e5e-000c-45d0-bcf2-78e023a60132',
    brand: 'none',
    name: 'DC Electric Motor',
    model: 'none',
    description: 'Unknown DC electric motor',
    bin: 'B4',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['electric', 'motor'],
    __typename: 'Part',
  },
]

export const seed = async () => {
  console.log(`Start seeding ...`)
  try {
    for (const partItem of partData) {
      const part = await prisma.part.create({
        data: partItem,
      })
      console.log(`Created part with id: ${part.name}`)
    }
  } catch (error) {
    console.error(error)
  } finally {
    await prisma.$disconnect()
    console.log(`Seeding finished.`)
  }
}

// export const seed = async () => {
//   console.log(`Start seeding ...`)
//   try {
//     const part = await prisma.part.create({
//       data: partData,
//     })
//     console.log(`Created part with id: ${part.name}`)
//   } catch (error) {
//     console.error(error)
//   } finally {
//     await prisma.$disconnect()
//     console.log(`Seeding finished.`)
//   }
// }

seed()
