import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const partData = [
  {
    id: 'f83eedae-cb14-453d-acc0-c37377838041',
    brand: 'none',
    name: 'small power switch',
    model: 'none',
    description: 'Small power switches',
    bin: 'A1',
    container: '01',
    location: 'closet',
    quantity: 75,
    tags: ['power', 'switch'],
    
  },
  {
    id: '47b66089-0dff-43a7-845d-1dd104b98168',
    brand: 'none',
    name: 'Momentary Push Button Tactile Switch',
    model: 'none',
    description:
      'Surface Mounted 4-Terminal Momentary Push Button Tactile Switch, 5 mm x 5 mm x 1.5 mm ',
    bin: 'A1',
    container: '01',
    location: 'closet',
    quantity: 68,
    tags: ['tact-switch', 'button'],
    
  },
  {
    id: '049f8eb7-79eb-463d-87fb-ba66b578753d',
    brand: 'uxcell',
    name: 'Momentary Push Button Tactile Switch',
    model: 'none',
    description:
      '5x5x1.5mm Momentary PCB Surface Mounted Devices SMT Mount 4 Pins Push Button SPST Tactile Tact Switch ',
    bin: 'A1',
    container: '01',
    location: 'closet',
    quantity: 30,
    tags: ['tact-switch', 'button'],
    
  },
  {
    id: '421c4fb9-9d62-4b3f-88db-11e96da4402d',
    brand: 'none',
    name: 'Red Led',
    model: 'Red',
    description: 'Red Led',
    bin: 'C1',
    container: '01',
    location: 'closet',
    quantity: 12,
    tags: ['electrical', 'led', 'light'],
    
  },
  {
    id: 'bdf6a8d4-4d9f-46df-b66f-8e0bfa0c98f7',
    brand: 'none',
    name: 'Diodes',
    model: 'none',
    description: 'Diodes',
    bin: 'C1',
    container: '01',
    location: 'closet',
    quantity: 3,
    tags: ['electrical', 'diodes'],
    
  },
  {
    id: '48dcc9be-b8e0-44b6-884b-cd20fa84a1e2',
    brand: 'none',
    name: 'Small LED light strip',
    model: 'none',
    description: 'Small LED light strip',
    bin: 'C1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['electrical', 'led', 'light'],
    
  },
  {
    id: 'd9ddd857-c8b8-4706-9329-0d593fa002be',
    brand: 'none',
    name: 'rubber dome tact switch',
    model: 'none',
    description: 'Rubber dome tact switch',
    bin: 'A1',
    container: '01',
    location: 'closet',
    quantity: 11,
    tags: ['tact-switch', 'rubber', 'dome'],
    
  },
  {
    id: '4ba06518-8700-4f5e-a4fc-f35db0f20fab',
    brand: 'none',
    name: 'Momentary Push Button Tactile Switch',
    model: 'none',
    description: 'Momentary Push Button Tactile Switch, 6 mm x 6 mm x 6 mm ',
    bin: 'A1',
    container: '01',
    location: 'closet',
    quantity: 13,
    tags: ['tact-switch', 'button'],
    
  },
  {
    id: 'ae146ead-7c6c-4562-8310-eda0a4891e24',
    brand: 'none',
    name: 'Misc. Hardware',
    model: 'none',
    description:
      'Misc. Hardware\n\nScrews, nuts, bolts, standoffs, washers, etc.',
    bin: 'A2',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['misc', 'hardware', 'nuts', 'bolts', 'washers', 'stand-offs'],
    
  },
  {
    id: '9dc5758f-3439-40ad-8ae6-de603e63bd2d',
    brand: 'none',
    name: 'small compression spring',
    model: 'none',
    description: 'Small compression springs',
    bin: 'A3',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['spring', 'compression', 'small'],
    
  },
  {
    id: '328b779f-0a62-4f8c-988e-1c6a1eee2764',
    brand: 'uxcell',
    name: 'Radial Ball Bearing',
    model: 'none',
    description:
      'uxcell a13061400ux0831 10 Pcs 625ZZ 5mm x 16mm x 5mm Shielded Deep Groove Radial Ball Bearing ',
    bin: 'A3',
    container: '01',
    location: 'closet',
    quantity: 8,
    tags: ['radial', 'bearing'],
    
  },
  {
    id: '5441baaa-d0a3-4daf-908f-bee05649b3b0',
    brand: 'uxcell',
    name: 'Radial Ball Bearing',
    model: '608',
    description:
      'VXB 608ZZ Set of 8 Skateboard Bearing 608Z Shielded Ball Bearings',
    bin: 'A3',
    container: '01',
    location: 'closet',
    quantity: 3,
    tags: ['radial', 'bearing', '608'],
    
  },
  {
    id: 'b4bbef9a-d18e-48c7-81bc-78bfc7f5a1b1',
    brand: 'FINDMAG',
    name: '5x3mm Magnet',
    model: '5x3mm',
    description: 'Magnets, 5x3mm',
    bin: 'A3',
    container: '01',
    location: 'closet',
    quantity: 62,
    tags: ['magnet'],
    
  },
  {
    id: '66aa9a99-2e4d-4c50-9efb-e966f8f8de71',
    brand: 'none',
    name: 'Misc. Magnets',
    model: 'none',
    description: 'Misc. Magnets',
    bin: 'A3',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['misc', 'magnets'],
    
  },
  {
    id: 'ca380494-b231-4c70-9820-88bd2c226918',
    brand: 'Yaxi',
    name: 'Yaxi Earpads',
    model: 'Black',
    description: 'YAXI EARPADS for Koss PORTAPRO (Black) ',
    bin: 'A4',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['Yaxi', 'Earpads'],
    
  },
  {
    id: '569bd881-8b65-4e2f-9fd9-fcf9eb6de90f',
    brand: 'Sunmns',
    name: '40mm Earpads',
    model: 'Black',
    description:
      'Sunmns 40mm Earpads Ear Pad Foam Cushion Cover Compatible with Motorola S305/ Sony Q21 Q23 Q23/ MDR-Q22LP/ MDR-Q33/ Panasonic RR930/ Logitech H555 Headphones, 5 Pairs, 1.61 x 1.61 x 0.31 inches',
    bin: 'A4',
    container: '01',
    location: 'closet',
    quantity: 8,
    tags: ['Earpads'],
    
  },
  {
    id: '4a9ddb7f-28d5-4db0-804f-965782e2518d',
    brand: 'none',
    name: 'Audio Adapter 6.35mm',
    model: 'none',
    description:
      'Audio Adapter 6.35mm (1/4 inch) Male to 3.5mm (1/8 inch) Female Stereo Headphone Connector',
    bin: 'A4',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['Audio', 'Adapter'],
    
  },
  {
    id: '14d76e41-0548-4d44-b066-d2374bec5a8d',
    brand: 'none',
    name: 'Misc. Nuts and Bolts',
    model: 'none',
    description: 'Misc. Nuts and bolts.',
    bin: 'B1',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['Misc', 'hardware', 'nuts', 'bolts'],
    
  },
  {
    id: '165d4093-15be-4701-90a9-bc5dc11baaf9',
    brand: 'none',
    name: 'PC Screws',
    model: 'none',
    description: 'PC Misc. Screws',
    bin: 'B2',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['Misc', 'PC'],
    
  },
  {
    id: 'f1c7474b-fcfa-4864-ab45-7e1b564079e8',
    brand: 'Arctic Silver',
    name: 'Arctic Silver 5',
    model: 'Arctic Silver 5',
    description: 'Arctic Silver 5 Thermal Paste',
    bin: 'B2',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['PC', 'thermal', 'paste'],
    
  },
  {
    id: '921092ed-7026-48b2-9451-2ea9b5519c10',
    brand: 'none',
    name: 'Wire Crimps',
    model: 'none',
    description: 'Wire crimps',
    bin: 'B3',
    container: '01',
    location: 'closet',
    quantity: 12,
    tags: ['electrical', 'crimps'],
    
  },
  {
    id: '478aa450-64d2-40f8-9c73-ee3ad659761f',
    brand: 'Gardner Bender',
    name: 'Ring Terminal',
    model: 'none',
    description: '16-14 AWG Ring Terminals',
    bin: 'B3',
    container: '01',
    location: 'closet',
    quantity: 22,
    tags: ['electrical', 'ring', 'terminal'],
    
  },
  {
    id: 'db1e49a5-8755-4c85-b8f0-fa8652872500',
    brand: 'none',
    name: 'Quick Connector',
    model: 'none',
    description: 'Wire quick connectors',
    bin: 'B3',
    container: '01',
    location: 'closet',
    quantity: 3,
    tags: ['electrical', 'quick', 'connector'],
    
  },
  {
    id: 'e3c37702-ee5f-4ff9-830b-e7658c4d1966',
    brand: 'Tulead',
    name: '12V DC Solenoid',
    model: '12V DC Solenoid',
    description:
      'Tulead 12V DC Solenoid Pull Push Electronic Actuator Micro Solenoid Electromagnet 5N Suction ',
    bin: 'B4',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['solenoid'],
    
  },
  {
    id: 'f8373f08-a9e4-442a-a88f-67e8af7a713f',
    brand: 'Topoox',
    name: 'Mini Electric Motor',
    model: 'DC 1.5-3V 15000RPM Mini Electric Motor',
    description: 'Topoox 6 Pack DC 1.5-3V 15000RPM Mini Electric Motor',
    bin: 'B4',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['electric', 'motor'],
    
  },
  {
    id: 'e350e54e-9e8e-4290-8104-2de1d62be14a',
    brand: 'ATNSINC',
    name: '28BYJ-48 Stepper Motor',
    model: '28BYJ-48',
    description: '6 PCS 28BYJ-48 ULN2003 5V Stepper Motor',
    bin: 'A5',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['stepper', 'motor'],
    
  },
  {
    id: '2e2f515b-f2bd-4594-8a03-8f3fd5d5271d',
    brand: 'ATNSINC',
    name: 'ULN2003 Driver Board',
    model: 'ULN2003',
    description: 'ULN2003 Driver Board',
    bin: 'A5',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['motor', 'driver', 'stepper'],
    
  },
  {
    id: '0294ba92-208b-4ce0-a753-24f8acef0316',
    brand: 'none',
    name: '200K Ohm Resistor',
    model: 'Fixed Resistor',
    description:
      '200K Ohm Resistor Color Code: Red, Black, Yellow, Golden. Resistance: 200K Ohm, Power Rating: 0.25 Watt, Approximate Maximum Current: 1.12mA',
    bin: 'C1',
    container: '01',
    location: 'closet',
    quantity: 75,
    tags: ['electrical', 'resistor'],
    
  },
  {
    id: '956691de-182b-421d-bde4-657b1945e379',
    brand: 'RadioShack',
    name: 'Rectangular Blue LED',
    model: '276-0013',
    description: 'Super High Brightness Rectangular Blue LED',
    bin: 'C1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['electrical', 'led', 'light'],
    
  },
  {
    id: 'fdba57a9-5d4e-43f0-87ae-1d76d09be0e5',
    brand: 'Deegoo',
    name: 'MG996R Digital Servo',
    model: 'MG996R',
    description:
      'Deegoo [4-Pack] MG996R 55g Metal Gear Torque Digital Servo Motor',
    bin: 'C2',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['Servo'],
    
  },
  {
    id: '4cb3c155-4afc-4df3-ae06-19eb1139e29a',
    brand: 'Philmore',
    name: '2.5mm DC Barrel Jack',
    model: '48-1297',
    description:
      '2.5mm DC Power Jack to solderless terminal. Accepts up to 14AWG wire.',
    bin: 'C3',
    container: '01',
    location: 'closet',
    quantity: 6,
    tags: ['electrical', 'power'],
    
  },
  {
    id: 'a5c7bf4c-18ff-45fb-830a-e7a6bc8e2bb6',
    brand: 'Deegoo',
    name: 'MG996R Electric Motor',
    model: 'MG996R Converted',
    description: 'MG996R Converted to high torque electric motors',
    bin: 'C4',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['electrical', 'motor'],
    
  },
  {
    id: 'c22df567-f4e6-4076-834d-860db4192189',
    brand: 'none',
    name: '3.5" composite screen',
    model: 'none',
    description: '3.5" composite screen',
    bin: 'A6',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['screen'],
    
  },
  {
    id: '16d08408-c5a0-42dc-8ccf-bb27565f8895',
    brand: 'none',
    name: '5" composite screen',
    model: 'none',
    description: '5" composite screen',
    bin: 'A6',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['screen'],
    
  },
  {
    id: 'bebf9c11-7a88-4502-9fe9-cc65510ad149',
    brand: 'none',
    name: 'L293D Motor Controller',
    model: 'L293D',
    description: 'L293D 16pin motor controller',
    bin: 'D1',
    container: '01',
    location: 'closet',
    quantity: 7,
    tags: ['electrical', 'motor', 'controller', 'ic'],
    
  },
  {
    id: '8b1c2439-5b31-4311-8c25-945cb39aa1d3',
    brand: 'KIALEDI',
    name: 'SG90 Servo Motor',
    model: 'SG90',
    description: 'Servo Motor SG90 Tower Pro 9g',
    bin: 'D2',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['servo'],
    
  },
  {
    id: '41f7b2ee-7bac-4873-805a-c094e4e5558a',
    brand: 'none',
    name: 'Disassembled mp3 player',
    model: 'none',
    description: 'Disassembled mp3 player',
    bin: 'D3',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['mp3', 'player'],
    
  },
  {
    id: 'c177141d-7a0c-4d70-84e1-206c460e8eb6',
    brand: 'none',
    name: 'Disassembled bluetooth controller',
    model: 'bluetooth controller',
    description: 'Disassembled bluetooth controller',
    bin: 'D3',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['bluetooth', 'controller'],
    
  },
  {
    id: '1d03ff2c-33f5-4fa9-a349-dbdd46f7f294',
    brand: 'Sony',
    name: 'PSP analog stick',
    model: 'PSP analog stick',
    description: 'PSP analog stick',
    bin: 'D3',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['psp', 'game', 'analog', 'stick'],
    
  },
  {
    id: '9231bb2a-7a89-4379-ac64-7a4fba30e0e6',
    brand: 'ANMBEST',
    name: 'USB C Port - Male',
    model: 'USB C Port - Male',
    description: 'USB C Port - Male with breakout',
    bin: 'D4',
    container: '01',
    location: 'closet',
    quantity: 4,
    tags: ['usb', 'c', 'breakout', 'power', 'charging'],
    
  },
  {
    id: 'd57f7344-d638-45b4-9e7d-b77b8d499a7b',
    brand: 'none',
    name: 'USB A Port - Female',
    model: 'USB A Port - Female',
    description: 'USB A Port - Female',
    bin: 'D4',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['usb', 'a', 'power', 'charging'],
    
  },
  {
    id: '4848fcb5-bf32-495c-9327-73b8a49dc783',
    brand: 'HiLetgo',
    name: 'FTDI Programmer',
    model: 'FT232RL',
    description:
      'HiLetgo FT232RL FTDI Mini USB to TTL Serial Converter Adapter Module 3.3V 5.5V FT232R Breakout FT232RL USB to Serial Mini USB to TTL Adapter Board',
    bin: 'E1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['ftdi', 'programmer', 'adapter', 'serial'],
    
  },
  {
    id: '285ae873-d861-468b-b5fc-2193b82d38e3',
    brand: 'Aideepen',
    name: 'FT232RL V2.0',
    model: 'FT232RL V2.0',
    description:
      'Aideepen FT232RL V2.0 Micro USB to TTL Serial Breakout Adapter Module Converter',
    bin: 'E1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['adapter', 'serial'],
    
  },
  {
    id: '6203057d-39c6-4213-9e68-d36b50ee95c7',
    brand: 'LICHIFIT',
    name: 'Game Cube SD2SP2',
    model: 'Game Cube SD2SP2',
    description:
      ' LICHIFIT Professional Micro SD Card Adapter TF Card Reader for Game Cube SD2SP2 SDLoad SDL Adapter (Blue) ',
    bin: 'E1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['gamecube', 'adapter'],
    
  },
  {
    id: 'cc2cac72-758b-46bc-93b4-97b959065e46',
    brand: 'XenoGC',
    name: 'XenoGC',
    model: 'XenoGC',
    description: 'XenoGC is a drivechip for the Nintendo Gamecube.',
    bin: 'E1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['gamecube', 'modchip'],
    
  },
  {
    id: '9cf5bdab-9298-4040-8fbb-a7cd0708da2e',
    brand: 'Adafruit',
    name: 'Mono Audio Amplifier',
    model: 'PAM8302',
    description:
      'Audio IC Development Tools Adafruit Mono 2.5W Class D Audio Amplifier - PAM8302',
    bin: 'E1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['audio', 'amp', 'mono'],
    
  },
  {
    id: '203e2317-b38f-43d8-8eb6-a05c6ef458da',
    brand: 'SH',
    name: 'Toggle Switch',
    model: '9345',
    description: 'Toggle Switch - 8A250V - 16A125V - 1HP 125V',
    bin: 'E2',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['toggle', 'switch', 'electrical', 'power'],
    
  },
  {
    id: '4f6b8405-6225-4a24-acb6-96c66163391b',
    brand: 'none',
    name: 'Rocker Switch',
    model: 'none',
    description: 'Rocker Switch - 10A 250VAC - 20A 128VAC',
    bin: 'E2',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['rocker', 'switch', 'electrical', 'power'],
    
  },
  {
    id: 'e1611bd3-ba8d-4747-8619-e58f65a9c3ef',
    brand: 'none',
    name: 'sh Button',
    model: 'Push Button',
    description: 'Momentary Push Button',
    bin: 'E2',
    container: '01',
    location: 'closet',
    quantity: 3,
    tags: ['button', 'electical'],
    
  },
  {
    id: '436ee303-6d4f-42c7-8f36-72298fb43d22',
    brand: 'none',
    name: 'Rocker Switch',
    model: 'none',
    description: 'Rocker Switch',
    bin: 'E2',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['rocker', 'switch', 'electrical', 'power'],
    
  },
  {
    id: '0bd75f48-cbe9-4a22-afd1-bb8cf5136225',
    brand: 'none',
    name: 'Wifi antenna',
    model: 'Wifi antenna',
    description: 'Wifi antenna',
    bin: 'E3',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['wifi', 'antenna'],
    
  },
  {
    id: 'cefc42b1-f8cb-4ea9-9995-1405a7d96fcd',
    brand: 'none',
    name: 'Small Heatsinks',
    model: 'none',
    description: 'Small Heatsinks',
    bin: 'E3',
    container: '01',
    location: 'closet',
    quantity: 7,
    tags: ['heatsinks', 'cooling'],
    
  },
  {
    id: '7917e9ad-eb9d-4a9a-8a7d-dd28baf969b7',
    brand: 'Adafruit',
    name: 'Mini Metal Speaker',
    model: 'Mini Metal Speaker',
    description: 'Mini Metal Speaker w/ Wires - 8 ohm 0.5W',
    bin: 'E3',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['speaker', 'audio'],
    
  },
  {
    id: 'e417bcfb-bf79-441b-9d01-67d67be93902',
    brand: 'ANMBEST',
    name: 'USB C Port - Female',
    model: 'USB C Port - Female',
    description: 'USB C Port - Female with breakout',
    bin: 'D4',
    container: '01',
    location: 'closet',
    quantity: 12,
    tags: ['usb', 'c', 'breakout', 'power', 'charging'],
    
  },
  {
    id: 'b8483f15-0d4a-4ce8-87e0-ed20c062b499',
    brand: 'none',
    name: 'Servo Adapters',
    model: 'none',
    description: 'Misc. Servo adapters and connections',
    bin: 'A7',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['misc', 'servo', 'adapters'],
    
  },
  {
    id: '9f0f4986-1e76-4152-b6c2-26d5664f6c72',
    brand: 'none',
    name: 'Potentiometer',
    model: 'none',
    description: 'Potentiometer',
    bin: 'A7',
    container: '01',
    location: 'closet',
    quantity: 4,
    tags: ['electrical', 'resistor'],
    
  },
  {
    id: '22579918-91a0-4562-9dc1-032eb431a35f',
    brand: 'DAOKI',
    name: '5V Battery Charging Protection Board',
    model: '134N3P',
    description:
      'DAOKI 5V Battery Charging Protection Board 1A Boost Step Up Power Supply Module 134N3P Lithium Battery Li-ion Charger Board',
    bin: 'E4',
    container: '01',
    location: 'closet',
    quantity: 5,
    tags: ['charging', 'power', 'electrical'],
    
  },
  {
    id: 'a56d9708-5ae3-4d49-9b33-fc1c06b32ada',
    brand: 'Tenergy',
    name: 'AA 2000mAh NiMH',
    model: 'P/N 10306',
    description: 'Tenergy AA 2000mAh NiMH Flat Top Rechargeable Battery',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 4,
    tags: ['battery', 'power', 'electrical'],
    
  },
  {
    id: '0ad84dc8-ec8f-4980-a96a-8b5823175ca1',
    brand: 'none',
    name: 'Li-ion Battery Pack',
    model: 'none',
    description: 'Li-ion battery pack - 3.7v - 570mAH/2Wh',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['battery', 'power', 'electrical'],
    
  },
  {
    id: 'be331827-860f-44ab-8aac-a6547b0f9054',
    brand: 'Synergy Digital',
    name: 'Synergy Digital Cordless Phone Battery',
    model: 'HGB-15AAx3',
    description:
      'Synergy Digital Cordless Phone Battery, Works with Huawei BTR2260B Cordless Phone, (Ni-MH, 3.6V, 1600 mAh) Ultra Hi-Capacity Battery ',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['battery', 'power', 'electrical'],
    
  },
  {
    id: 'f3b912a9-a8f7-40aa-992e-9daf4cb456a3',
    brand: 'Adafruit',
    name: 'Adafruit 328 Battery',
    model: 'Adafruit 328 Battery',
    description:
      'Adafruit 328 Battery, Lithium Ion Polymer, 3.7V, 2500mAh, 2" x 2.55" x 0.30" Size',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['battery', 'power', 'electrical'],
    
  },
  {
    id: '5fe22726-31f5-476e-96e5-e3b86f371bfd',
    brand: 'none',
    name: 'SP65M 3.7V 2210mAh Battery',
    model: 'SP65M',
    description:
      'SP65M 3.7V 2210mAh Battery Replacement for Sony Playstation PS Vita PCH-1001 PCH-1101 1003 1103',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['battery', 'power', 'electrical'],
    
  },
  {
    id: 'aff3cc8f-a0a3-402a-a2ec-69fad2a60d1b',
    brand: 'none',
    name: 'Battery - 3.7V 4000MAH',
    model: '805080 3.7V 4000MAH',
    description: '805080 3.7V 4000MAH Polymer cell battery',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['battery', 'power', 'electrical'],
    
  },
  {
    id: '4ece5a0f-53d5-4bfe-bc65-aabc54618d40',
    brand: 'none',
    name: 'IDE Cable',
    model: 'IDE Cable',
    description: 'IDE Cable',
    bin: 'C6',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['IDE', 'wire'],
    
  },
  {
    id: '0b7aab88-e178-4e66-9a86-4608d46a29ca',
    brand: 'none',
    name: 'Misc. Wire',
    model: 'none',
    description: 'Misc. Wire',
    bin: 'C6',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['misc', 'wire'],
    
  },
  {
    id: '09eaeeb2-e0f5-4615-b59d-a8b016a58faa',
    brand: 'none',
    name: '3.5mm Headphone Jack (TRRS)',
    model: 'none',
    description: '3.5mm TRRS headphone jack',
    bin: 'A4',
    container: '01',
    location: 'closet',
    quantity: 3,
    tags: ['trrs'],
    
  },
  {
    id: 'a3dfe546-94cb-41cf-adec-d3517f0f92fc',
    brand: 'none',
    name: 'Misc. Power Connectors',
    model: 'none',
    description: 'Misc. Power Connectors',
    bin: 'C6',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['misc', 'connectors'],
    
  },
  {
    id: '1c20211e-843f-49d5-aa16-127726aa6c62',
    brand: 'none',
    name: 'Male Barrel Jack Plugs',
    model: 'none',
    description: 'Variable Male Barrel Jack Plugs of different sizes',
    bin: 'C3',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['barrel', 'jack', 'power', 'electrical'],
    
  },
  {
    id: 'c993a8f4-3d06-41de-8bc7-67fde1722593',
    brand: 'Adafruit',
    name: 'PiGRRL 2.0 Custom Gamepad PCB',
    model: 'Product ID: 3015',
    description: 'PiGRRL 2.0 Custom Gamepad PCB',
    bin: 'C5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['gamepad', 'buttons', 'pigrrl'],
    
  },
  {
    id: '39556e5e-000c-45d0-bcf2-78e023a60132',
    brand: 'none',
    name: 'DC Electric Motor',
    model: 'none',
    description: 'Unknown DC electric motor',
    bin: 'B4',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['electric', 'motor'],
    
  },
  {
    id: '602621ea-46a8-487d-9f35-27ee9b0cca10',
    brand: 'SUTEMRIBOR',
    name: 'M3x16mm Bolt',
    model: 'M3x16mm',
    description: 'M3 Button Head Socket Cap Bolts',
    bin: 'C7',
    container: '01',
    location: 'closet',
    quantity: 60,
    tags: ['metric', 'bolt', 'hardware', 'screws'],
    
  },
  {
    id: 'f3d7b37a-ff99-4307-bca9-28e61db98147',
    brand: 'SUTEMRIBOR',
    name: 'M3x20mm Bolt',
    model: 'M3x20mm',
    description: 'M3 Button Head Socket Cap Bolts',
    bin: 'C7',
    container: '01',
    location: 'closet',
    quantity: 60,
    tags: ['metric', 'bolt', 'hardware', 'screws'],
    
  },
  {
    id: '82c5a28a-f194-4810-bb6d-0a470669918d',
    brand: 'SUTEMRIBOR',
    name: 'M3x5mm Bolt',
    model: 'M3x5mm',
    description: 'M3 Button Head Socket Cap Bolts',
    bin: 'C7',
    container: '01',
    location: 'closet',
    quantity: 80,
    tags: ['metric', 'bolt', 'hardware', 'screws'],
    
  },
  {
    id: '9446952a-e9f9-48c9-a56c-f8ebedf66c0c',
    brand: 'SUTEMRIBOR',
    name: 'M3x6mm Bolt',
    model: 'M3x6mm',
    description: 'M3 Button Head Socket Cap Bolts',
    bin: 'C7',
    container: '01',
    location: 'closet',
    quantity: 60,
    tags: ['metric', 'bolt', 'hardware', 'screws'],
    
  },
  {
    id: '47e1a91a-64de-42ca-b97d-127977dea0f8',
    brand: 'SUTEMRIBOR',
    name: 'M3x8mm Bolt',
    model: 'M3x8mm',
    description: 'M3 Button Head Socket Cap Bolts',
    bin: 'C7',
    container: '01',
    location: 'closet',
    quantity: 60,
    tags: ['metric', 'bolt', 'hardware', 'screws'],
    
  },
  {
    id: 'e9f7c6d6-2a37-45e1-9795-015c4ee0b819',
    brand: 'SUTEMRIBOR',
    name: 'M3x12mm Bolt',
    model: 'M3x12mm',
    description: 'M3 Button Head Socket Cap Bolts',
    bin: 'C7',
    container: '01',
    location: 'closet',
    quantity: 60,
    tags: ['metric', 'bolt', 'hardware', 'screws'],
    
  },
  {
    id: '2fb3c902-d4c8-4f82-a899-3d7ec67eb874',
    brand: 'SUTEMRIBOR',
    name: 'M3 Nut',
    model: 'M3',
    description: 'M3 Nuts',
    bin: 'C7',
    container: '01',
    location: 'closet',
    quantity: 260,
    tags: ['metric', 'hardware', 'nut'],
    
  },
  {
    id: '9cebfe8e-9941-4881-be58-376209b6e956',
    brand: 'misc',
    name: 'SD Card adapter',
    model: 'SD Card adapter',
    description: 'Micro SD to full size SD Card adapter',
    bin: 'E5',
    container: '01',
    location: 'closet',
    quantity: 19,
    tags: ['flash', 'storage', 'sd', 'adapter'],
    
  },
  {
    id: '7a81a76e-182e-42b8-a296-72a1b1e564f9',
    brand: 'Kingston',
    name: '32gb Micro SD Card',
    model: 'Kingston Canvas Select Plus',
    description: 'Kingston Canvas Select Plus 32gb Micro SD Card',
    bin: 'E5',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['flash', 'storage', 'micro', 'sd'],
    
  },
  {
    id: '074f5c45-a9fc-42aa-b1c3-6ea9e57a694b',
    brand: 'Micro Center',
    name: '64gb Micro SD Card',
    model: '64gb Micro SD Card',
    description: 'Micro Center 64gb class 10 Micro SD Card',
    bin: 'E5',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['flash', 'storage', 'micro', 'sd'],
    
  },
  {
    id: '82357f33-1405-40ad-b095-4b84136e01b4',
    brand: 'SanDisk',
    name: '512mb Micro SD Card',
    model: 'SanDisk 512mb Micro SD Card',
    description: 'SanDisk 512mb Micro SD Card',
    bin: 'E5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['flash', 'storage', 'micro', 'sd'],
    
  },
  {
    id: '18cc8779-3204-48f7-b66a-16618c12c695',
    brand: 'PNY',
    name: '2gb Micro SD Card',
    model: 'PNY 2gb Micro SD Card',
    description: 'PNY 2gb Micro SD Card',
    bin: 'E5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['flash', 'storage', 'micro', 'sd'],
    
  },
  {
    id: 'cb5b2266-d746-47d3-aa93-a5b04d7d13f8',
    brand: 'SanDisk',
    name: '2gb Full SIze SD Card',
    model: 'Full SIze SD Card',
    description: 'SanDisk 2gb Full SIze SD Card',
    bin: 'E5',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['sd', 'storage', 'fullsize', 'flash'],
    
  },
  {
    id: 'ee835858-1c85-446b-b48e-9a2de826b4bf',
    brand: 'SanDisk',
    name: '16gb Micro SD Card',
    model: 'Ultra',
    description: 'SanDisk Ultra 16gb Micro SD Card',
    bin: 'E5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['flash', 'storage', 'micro', 'sd'],
    
  },
  {
    id: '2838b8b4-3ce1-4cf8-b785-d419c087dfd5',
    brand: 'Toshiba',
    name: '4gb Micro SD Card',
    model: 'C04G',
    description: 'Toshiba 4gb Class 4 (SDHC) Micro SD Card',
    bin: 'E5',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['flash', 'storage', 'micro', 'sd', 'sdhc'],
    
  },
  {
    id: '2077cd9f-2174-47dd-a489-5bbb0ac6c97c',
    brand: 'DANE-ELEC',
    name: '8gb Flash Drive',
    model: 'none',
    description: '8gb Flash Drive - USB A',
    bin: 'F4',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['flash', 'storage', 'usb', 'drive'],
    
  },
  {
    id: 'b79aeeb7-758e-4751-b52e-a9dea415b6b4',
    brand: 'DANE',
    name: '32gb Flash Drive',
    model: 'none',
    description: '32gb Flash Drive - USB A',
    bin: 'F4',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['flash', 'storage', 'usb', 'drive'],
    
  },
  {
    id: '6118e270-a773-481c-8d59-d4152049bc8d',
    brand: 'none',
    name: '16gb Flash Drive',
    model: 'Minion',
    description: 'Minion 16gb Flash Drive USB A',
    bin: 'F4',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['flash', 'storage', 'usb', 'drive'],
    
  },
  {
    id: '2d733bdd-a996-4e41-8d01-e1295b905547',
    brand: 'PNY',
    name: '16gb Flash Drive',
    model: 'none',
    description: '16gb Flash Drive - USB A (Green)',
    bin: 'F4',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['flash', 'storage', 'usb', 'drive'],
    
  },
  {
    id: '87607495-a48d-448d-8ec3-08ffcde7f368',
    brand: 'Micro Center',
    name: '128gb Flash Drive',
    model: 'none',
    description: '128gb Flash Drive - USB A - USB 3.1',
    bin: 'F4',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['flash', 'storage', 'usb', 'drive', '3.1'],
    
  },
  {
    id: '53bd2c00-9c60-4966-a1cf-a5940e9d82b9',
    brand: 'SanDisk',
    name: '32gb Flash Drive',
    model: 'Ultra',
    description: 'SanDisk Ultra USB 3.0 32GB Flash Drive - USB A - USB 3.0',
    bin: 'F4',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['flash', 'storage', 'usb', 'drive', '3.0'],
    
  },
  {
    id: '86e5bcd0-8f23-4f8d-b52b-e08e9c581cd0',
    brand: 'PNY',
    name: '16gb Flash Drive',
    model: 'none',
    description: '16gb Flash Drive - USB A',
    bin: 'F4',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['flash', 'storage', 'usb', 'drive'],
    
  },
  {
    id: '98e86c3c-797e-4316-a33d-2820e0ceb609',
    brand: 'D-Link',
    name: 'Wireless Dongle',
    model: 'none',
    description: 'Wifi and Bluetooth USA A dongle',
    bin: 'F4',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['wifi', 'bluetooth', 'usb', 'dongle'],
    
  },
  {
    id: '08a67a6f-6268-4b38-83b3-b6383ca437b8',
    brand: 'Plugable',
    name: 'Wireless Dongle',
    model: 'none',
    description: 'Wifi and Bluetooth USA A dongle',
    bin: 'F4',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['wifi', 'bluetooth', 'usb', 'dongle'],
    
  },
  {
    id: '381abb13-c343-4f42-baec-a8a176496383',
    brand: 'none',
    name: 'Wireless Dongle',
    model: 'CSR 4.0',
    description: 'Wifi and Bluetooth USA A dongle',
    bin: 'F4',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['wifi', 'bluetooth', 'usb', 'dongle'],
    
  },
  {
    id: '6b2c2e45-f831-4b1b-bcef-73cd061486b1',
    brand: 'none',
    name: 'Misc. USB, SATA, and Networking Adapters',
    model: 'none',
    description: 'Misc. USB, SATA, and Networking Adapters',
    bin: 'E6',
    container: '01',
    location: 'closet',
    quantity: 0,
    tags: ['misc', 'adapters'],
    
  },
  {
    id: 'ab219814-4006-44d9-aae1-380379249ecf',
    brand: 'none',
    name: '1tb External SSD',
    model: 'none',
    description: '1tb External SSD',
    bin: 'F1',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['ssd', 'external', 'storage'],
    
  },
  {
    id: 'b6d7aa26-e0e0-4152-8839-4b4ac03d2c19',
    brand: 'Schmart Board',
    name: 'Single Row Headers',
    model: '1x40 Single Row',
    description: '1x40 Single Row Headers',
    bin: 'F2',
    container: '01',
    location: 'closet',
    quantity: 10,
    tags: ['headers', 'pins'],
    
  },
  {
    id: '17781954-b162-4954-839e-69e5f6062c79',
    brand: 'none',
    name: 'Arduino MEGA 2560',
    model: 'Arduino MEGA 2560',
    description: 'Arduino MEGA 2560 R3 Micro Controller',
    bin: 'E7',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['arduino', 'microcontroller'],
    
  },
  {
    id: 'b374eada-90f1-4a71-a4cb-6f61cad32721',
    brand: 'AiTRIP',
    name: 'ESP32-CAM',
    model: 'ESP32-CAM',
    description:
      'AiTrip ESP32-CAM WiFi + Bluetooth Module Development Board with OV2640 Camera Module ',
    bin: 'E7',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['ESP32', 'Microcontroller', 'wifi', 'bluetooth', 'camera'],
    
  },
  {
    id: '8631a2ff-9ce3-4d87-be5c-8804c5e3d84e',
    brand: 'none',
    name: 'ESP32',
    model: 'none',
    description: 'ESP32 with onboard JST connector',
    bin: 'E7',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['ESP32', 'Microcontroller', 'wifi', 'bluetooth'],
    
  },
  {
    id: 'c79e0f8d-e6b0-4393-942f-f584a6362747',
    brand: 'Inland',
    name: 'ESP32',
    model: 'ESP-WROOM-32',
    description: 'ESP32 micro controller core development board',
    bin: 'E7',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['ESP32', 'Microcontroller', 'wifi', 'bluetooth'],
    
  },
  {
    id: '30bb4b3d-2710-457b-82cb-06a2bb65cfc8',
    brand: 'HiLetgo',
    name: 'Digital Temperature Humidity Sensor ',
    model: 'DHT11',
    description:
      'DHT11 Temperature Humidity Sensor Module Digital Temperature Humidity Sensor 3.3V-5V Humidity Measure Range 20%-95% Temperature Measure Range 0-50℃ Celsius with Dupont Wires',
    bin: 'G6',
    container: '01',
    location: 'closet',
    quantity: 5,
    tags: ['esp32', 'arduino', 'sensor', 'temperature', 'moisture', 'humidity'],
    
  },
  {
    id: 'cb53edf9-c2bb-4efd-84b5-39a250e53221',
    brand: 'none',
    name: 'NFC Tag Programmer',
    model: 'none',
    description: 'NFC Tag Programmer',
    bin: 'G6',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['NFC', 'programmer'],
    
  },
  {
    id: '0f090bea-b0c0-452f-815e-f6dcfcac708f',
    brand: 'Raspberry Pi',
    name: 'Raspberry Pi Zero',
    model: 'Zero',
    description: 'Raspberry Pi Zero',
    bin: 'G7',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['raspberrypi', 'sbc'],
    
  },
  {
    id: 'ad11a931-148e-4063-87a1-016fc970727a',
    brand: 'Raspberry Pi',
    name: 'Raspberry Pi Zero W',
    model: 'Zero W',
    description: 'Raspberry Pi Zero W with Wifi and Bluetooth',
    bin: 'G7',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['raspberrypi', 'sbc', 'wireless', 'wifi', 'bluetooth'],
    
  },
  {
    id: '0d69bc47-8020-457a-8112-efe82b99d748',
    brand: 'Raspberry Pi',
    name: 'Raspberry Pi Pico',
    model: 'Pico',
    description: 'Raspberry Pi Pico Microcontroller',
    bin: 'G7',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['raspberrypi', 'microcontroller'],
    
  },
  {
    id: '8df29d36-d120-4339-ae6d-8e840080bfd1',
    brand: 'Raspberry Pi',
    name: 'Raspberry Pi Pico W',
    model: 'Pico W',
    description: 'Raspberry Pi Pico W Microcontroller with Wifi and Bluetooth',
    bin: 'G7',
    container: '01',
    location: 'closet',
    quantity: 2,
    tags: ['raspberrypi', 'microcontroller', 'wireless', 'wifi', 'bluetooth'],
    
  },
  {
    id: 'db8b6a48-2a41-4c8b-bc36-c1558d206697',
    brand: 'Raspberry Pi',
    name: 'Raspberry Pi - Model B',
    model: 'B',
    description: 'Raspberry Pi - Model B Single Board Computer',
    bin: 'G7',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['raspberrypi', 'sbc'],
    
  },
  {
    id: '41ad01fd-4945-4fc6-8e97-7c1b602dc7e7',
    brand: 'Raspberry Pi',
    name: 'Raspberry Pi 3 - Model B+',
    model: 'B+',
    description:
      'Raspberry Pi 3 - Model B+ Single Board Computer Wifi and Bluetooth',
    bin: 'G7',
    container: '01',
    location: 'closet',
    quantity: 1,
    tags: ['raspberrypi', 'sbc', 'wireless', 'wifi', 'bluetooth'],
    
  },
]

export const seed = async () => {
  console.log(`Start seeding ...`)
  try {
    for (const partItem of partData) {
      const part = await prisma.part.create({
        data: partItem,
      })
      console.log(`Created part with id: ${part.name}`)
    }
  } catch (error) {
    console.error(error)
  } finally {
    await prisma.$disconnect()
    console.log(`Seeding finished.`)
  }
}

seed()
